app:
  image: 'mhart/alpine-node:6.7'
  working_dir: '/app'
  command: "npm run dev"
  #command: "npm run dev:server" #if you don't want clientkit
  volumes:
    - '.:/app'
  environment:
    PORT: 8080
    VIRTUAL_HOST: 'changeme.*'
  ports:
    - '8080'
  links:
    - 'mongo:mongo'
mongo:
  image: 'mongo'
  command: 'mongod --smallfiles --quiet'
